#!/bin/bash
echo "🔧 Installing SigScan extension in development mode..."
echo ""
echo "To test the gas fix, follow these steps:"
echo ""
echo "1. Open VS Code"
echo "2. Press F5 (or Run > Start Debugging)"
echo "3. This will open a new VS Code window with the extension loaded"
echo "4. Open a Solidity file (like examples/SimpleStorage.sol)"
echo "5. Check the gas annotations next to functions"
echo ""
echo "Or manually install from VSIX:"
echo "  code --install-extension $(pwd)/sigscan-0.0.5.vsix --force"
echo ""
